import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/providers/themeProvider";
import Sidebar from "@/components/Sidebar";


const inter = Inter({subsets: ["greek-ext"]});

export const metadata: Metadata = {
    title: "Clone demo",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;


}>) {
    return (
        <html lang="en">
        <body
            className={inter.className}
        >
        {/*<ThemeProvider*/}
        {/*    attribute="class"*/}
        {/*    defaultTheme="System"*/}
        {/*    enableSystem*/}
        {/*    disableTransitionOnChange*/}
        {/*>*/}
            <Sidebar>
                {children}
            </Sidebar>
        {/*</ThemeProvider>*/}
        </body>
        </html>
    );
}
